[build]
    command = "dotnet publish ballstore.csproj -c Release -o publish"
    publish = "publish"
    functions = "netlify/functions"

[[redirects]]
    from = "/*"
    to = "/index.html"
    status = 200